easy_admin:   
   entities:
       # List the entity class name you want to manage
      #  - App\Entity\Product
      Category:
            class: App\Entity\Category
            Label: 'Catégorie'
            form:
                fields:
                    - {property: 'name'}
                    - {property: 'slug'}